In [2]:


import pandas as pd
import numpy as np





df = pd.read_csv('../Dataset/Census2.csv')

df1 = pd.read_csv('../Dataset/Bi and Tri Age2.csv')

df1 = df1[df1['Type']== 'Total']
df1 = df1[df1['Age Group'] == 'Total']

df1.head()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30

IndexError: single positional indexer is out-of-bounds

In [6]:
df.head(250)
##df[df['State Code']== 31]['TOT_P'].iloc[0]

    State Code                 State Name       TOT_P      TOT_M      TOT_F
0            0                      INDIA  1215574677  626065355  589509322
1            1            JAMMU & KASHMIR    12541302    6640662    5900640
2            2           HIMACHAL PRADESH     6864602    3481873    3382729
3            3                     PUNJAB    27743338   14639465   13103873
4            4                 CHANDIGARH     1055450     580663     474787
5            5                UTTARAKHAND    10086292    5137773    4948519
6            6                    HARYANA    25351462   13494734   11856728
7            7                      DELHI    33575882   17974652   15601230
8            8                  RAJASTHAN    68548437   35550997   32997440
9            9              UTTAR PRADESH   196821531  102935702   93885829
10          10                      BIHAR   104099452   54278157   49821295
11          11                     SIKKIM      610577     323070     287507
12          12          ARUNACHAL PRADESH     1383727     713912     669815
13          13                   NAGALAND     1978502    1024649     953853
14          14                    MANIPUR     2855794    1438586    1417208
15          15                    MIZORAM     1097206     555339     541867
16          16                    TRIPURA     3673917    1874376    1799541
17          17                  MEGHALAYA     2966889    1491832    1475057
18          18                      ASSAM    31205576   15939443   15266133
19          19                WEST BENGAL    91276115   46809027   44467088
20          20                  JHARKHAND    31923078   16385904   15537174
21          21                     ODISHA    41974218   21212136   20762082
22          22               CHHATTISGARH    23263525   11674085   11589440
23          23             MADHYA PRADESH    72626809   37612306   35014503
24          24                    GUJARAT    60439692   31491260   28948432
25          25                DAMAN & DIU      243247     150301      92946
26          26       DADRA & NAGAR HAVELI      343709     193760     149949
27          27                MAHARASHTRA   108578924   56292926   52285998
28          28             ANDHRA PRADESH    84580777   42442146   42138631
29          29                  KARNATAKA    58917966   29855635   29062331
30          30                        GOA     1458545     739140     719405
31          32                     KERALA    33406061   16027412   17378649
32          33                 TAMIL NADU    72147030   36137975   36009055
33          34                 PUDUCHERRY     1489991     729463     760528
34          35  ANDAMAN & NICOBAR ISLANDS      380581     202871     177710

In [ ]:


data ={}
df3 = pd.DataFrame()
for i in df1['State Code'] :
    data['State Code'] = i 
    
    data['State Name'] = df1[df1['State Code']== i]['State Name'].iloc[0]
    data['One Total'] = df[df['State Code']== i]['TOT_P'].iloc[0] - (df1[df1['State Code']== i]['Two Total'].iloc[0] + df1[df1['State Code']== i]['Three Total'].iloc[0])
    data['One Male'] = df[df['State Code']== i]['TOT_M'].iloc[0] - (df1[df1['State Code']== i]['Two Male'].iloc[0] + df1[df1['State Code']== i]['Three Male'].iloc[0])
    data['One Female'] = df[df['State Code']== i]['TOT_F'].iloc[0] - (df1[df1['State Code']== i]['Two Female'].iloc[0] + df1[df1['State Code']== i]['Three Female'].iloc[0])
    print(i)
    df3 = df3.append(data,ignore_index=True)

df3 = df3[['State Code', 'State Name' , 'One Total' , 'One Male' , 'One Female']]
##df3.to_csv('../Dataset/Mono Gender.csv',index=False)